# Generated by Django 3.0 on 2023-06-25 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverDueCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdue', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'overdue charges',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images//%Y/%m/%d/')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('sms_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('staff_id', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name_plural': 'staff',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images//%Y/%m/%d/')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('sms_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('student_id', models.CharField(max_length=15, unique=True)),
                ('level', models.CharField(choices=[('remedials', 'Remedials'), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'students',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='YearOfAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name_plural': 'years of admission',
            },
        ),
        migrations.CreateModel(
            name='StudentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book title')),
                ('issued_date', models.DateTimeField(default=datetime.datetime(2023, 6, 25, 17, 21, 2, 356213))),
                ('added_days', models.IntegerField(blank=True, null=True)),
                ('remaining_days', models.CharField(blank=True, max_length=100, null=True)),
                ('expiring_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 9, 17, 21, 2, 356321), null=True)),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Student')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.YearOfAdmission'),
        ),
        migrations.CreateModel(
            name='StaffBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book title')),
                ('issued_date', models.DateTimeField(default=datetime.datetime(2023, 6, 25, 17, 21, 2, 356213))),
                ('added_days', models.IntegerField(blank=True, null=True)),
                ('remaining_days', models.CharField(blank=True, max_length=100, null=True)),
                ('expiring_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 9, 17, 21, 2, 356321), null=True)),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Staff')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
