# Generated by Django 3.0 on 2023-06-29 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images//%Y/%m/%d/')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('sms_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('id_number', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name_plural': 'staff',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images//%Y/%m/%d/')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('sms_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('id_number', models.CharField(max_length=15, unique=True)),
                ('year_of_admission', models.CharField(max_length=8, null=True)),
                ('level', models.CharField(choices=[('remedials', 'Remedials'), ('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'students',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book title')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('added_days', models.IntegerField(blank=True, null=True)),
                ('remaining_days', models.CharField(blank=True, max_length=100, null=True)),
                ('expiring_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 16, 34, 0, 825462, tzinfo=utc), null=True)),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Student')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book title')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('added_days', models.IntegerField(blank=True, null=True)),
                ('remaining_days', models.CharField(blank=True, max_length=100, null=True)),
                ('expiring_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 16, 34, 0, 825462, tzinfo=utc), null=True)),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Staff')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
