# Generated by Django 3.0 on 2023-06-29 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20230629_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_of_admission',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='staffbook',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 19, 7, 30, 129146, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='studentbook',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 19, 7, 30, 129146, tzinfo=utc), null=True),
        ),
    ]
