# Generated by Django 3.0 on 2023-06-29 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20230629_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id_number',
        ),
        migrations.AlterField(
            model_name='staffbook',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 19, 15, 51, 221420, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='studentbook',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 13, 19, 15, 51, 221420, tzinfo=utc), null=True),
        ),
    ]
