# Generated by Django 3.0 on 2023-07-01 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20230629_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbook',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 15, 16, 7, 47, 539076, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='studentbook',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 15, 16, 7, 47, 539076, tzinfo=utc), null=True),
        ),
    ]
