# Generated by Django 3.0 on 2023-06-25 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20230625_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbook',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 9, 17, 36, 43, 27405), null=True),
        ),
        migrations.AlterField(
            model_name='staffbook',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 17, 36, 43, 27266)),
        ),
        migrations.AlterField(
            model_name='studentbook',
            name='expiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 9, 17, 36, 43, 27405), null=True),
        ),
        migrations.AlterField(
            model_name='studentbook',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 17, 36, 43, 27266)),
        ),
    ]
