# Generated by Django 3.0 on 2023-06-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20230625_1740'),
        ('books', '0008_auto_20230625_1736'),
    ]

    operations = [
    ]
